ros__parameters:
  joint_limits:
    front_left_wheel_steer_joint:
      has_acceleration_limits: false
      has_jerk_limits: false
      has_position_limits: true
      min_position: -0.61087
      max_position: 0.46251

    front_right_wheel_steer_joint:
      has_acceleration_limits: false
      has_jerk_limits: false
      has_position_limits: true
      min_position: -0.61087
      max_position: 0.46251
