controller_manager:
  ros__parameters:
    update_rate: 30
    
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
ackermann_steering_controller:
  ros__parameters:
    base_frame_id: base_link
    reference_timeout: 2.0
    front_steering: true
    open_loop: true
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_wheel_steer_joint, front_left_wheel_steer_joint]

    wheelbase: 0.26
    front_wheel_track: 0.198
    rear_wheel_track: 0.204
    front_wheels_radius: 0.45
    rear_wheels_radius: 0.45

# joint_broad:
#   ros__parameters: